# Generated by Django 4.2.6 on 2023-10-11 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmer',
            options={'verbose_name_plural': 'Farmers'},
        ),
    ]
