# Generated by Django 4.2.6 on 2023-10-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_location_user_location_geo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location_geo',
            field=models.JSONField(default={}, null=True),
        ),
    ]
