# Generated by Django 4.2.6 on 2023-10-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='product',
            field=models.ManyToManyField(null=True, to='core.product'),
        ),
    ]
